version: '3'
services:
  mongodb:
    image: mongo:7.0.4
    container_name: ${MONGO_CONTAINER_NAME_DEV}
    ports:
      - ${MONGO_PORT_DEV}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER_DEV}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS_DEV}